customhost = "employee.cxhbb0chwoos.us-west-2.rds.amazonaws.com"
customuser = "loukik"
custompass = "loukik1234"
customdb = "employee"
custombucket = "addemployee12"
customregion = "oregon"
customtable = "us-west-2"
